### ISSUE TITLE
Interruption doesn't work on fibers which have used bracket

### ISSUE THREAD

**Issue by adamw** [scalaz/scalaz-zio#64]
It's not that easy to reproduce but here's the minimal example I arrived at:

```
object X extends App with RTS {
  import scala.concurrent.duration._

  val c = new AtomicInteger(0)

  val test: IO[Throwable, Unit] = IO
    .syncThrowable {
      println(System.currentTimeMillis() + " working")
      Thread.sleep(100)
      if (c.incrementAndGet() <= 1) {
        throw new RuntimeException("x")
      } else {
        ()
      }
    }
    .forever
    .ensuring(IO.sync(println("CLEANUP; RESTARTING")))
    .attempt
    .forever

  unsafePerformIO[Void, Unit](
    test
      .fork[Void]
      .flatMap(f => IO.sleep[Void](1.second) *> f.interrupt(new RuntimeException("y"))))
}
```

Even though the fiber is interrupted after 1 second, it ends up printing `working` infinitely. Interruption works correctly if the bracket (`ensuring`) never runs (so if `throw new RuntimeException("x")` is never executed) or if there's no bracket at all.

The double-forever-loop is there as the original concept was to acquire a resource, use it in a loop, and if there's an error clean up and acquire again (hence the second loop).

**Comment by jdegoes** [comment]
@wi101 We'll have to clean this up and put it into a test.

As far as I can tell from a preliminary look, the correct behavior should be:

 * Prints out "working"
 * Prints out "CLEANUP; RESTARTING"
 * Prints out "working" _about_ 9 times (it's non-deterministic exactly how many)
 * Interrupts and terminates with `RuntimeException("y")` after printing "CLEANUP; RESTARTING" one more time

We can eliminate the print lines, reduce the timeouts, and see if we can chop anything else out in the test case.

**Comment by wi101** [comment]
This test case without `throw new RuntimeException("x")` works correctly.
We have a problem if the release had a failed result in Bracket.

@jdegoes I will commit the change, the behavior now is exactly like you mentioned ! (in the third step "working" appears exactly 9 times! 😁 )

**Comment by wi101** [comment]
@jdegoes I couldn't apply the change because the test cases in RTSSpec of brackets will fail, 
I wanted to do this in RTS at the case of `Bracket`
```scala
             curIo = for {
                      a <- (for {
                            a <- io.acquire
                            _ <- IO.sync(ref.set(a))
                          } yield a).uninterruptibly
                      b <- io.use(a).attempt
                      _ <- ((b match {
                            case Right(r) => io.release(ExitResult.Completed(r), a)[E]
                            case Left(e)  => io.release(ExitResult.Failed(e), a)[E]
                          }) <* IO.sync(ref.set(null))).uninterruptibly
                    } yield b
```

**Comment by jdegoes** [comment]
@wi101 Maybe we will defer this one a bit until after the `Finalizer` changes are in. I have a feeling I may know what the core bug is here (but maybe not), which is non-interruption.

**Comment by jdegoes** [comment]
@adamw Should be fixed now. Was introduced in the ZIO port but now there's a regression test case in there.

**Comment by adamw** [comment]
@jdegoes thanks! this passes, though the 'big' test (https://github.com/softwaremill/akka-vs-scalaz/blob/master/core/src/test/scala/com/softwaremill/supervise/ZioSuperviseTest.scala) still fails (the interruption doesn't stop the fiber). I'll try to create another test case next week.
